version: '3.8'
services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - vite-network

networks:
  vite-network:
    driver: bridge